name-template: 'v$NEXT_PATCH_VERSION ğŸŒˆ'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
categories:
  - title: 'ğŸš€ New'
    label: 'type: enhancement'
  - title: 'ğŸ› Bug Fixes'
    label: 'type: bug'
  - title: 'ğŸ§° Maintenance'
    label: 'type: chore'
  - title: 'Documentation'
    label: 'type: documentation'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
