name-template: 'v$NEXT_PATCH_VERSION ğŸŒˆ'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES  
categories:
  - title: 'â— Breaking'
    label: 'type: breaking'
  - title: 'ğŸš€ New'
    label: 'type: feature'
  - title: 'ğŸ› Bug Fixes'
    label: 'type: bug'
  - title: 'ğŸ§° Maintenance'
    label: 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'
